# Specify reviewers for pull requests

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
