package:
  name: supymode
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/MartinPdeS/SuPyMode.git

build:
  number: 0
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
    - numpy >=2.0,<3
  run:
    - martinpdes::pyoptik
    - martinpdes::mpsplots
    - martinpdes::fiberfusing
    - martinpdes::pyfibermodes
    - martinpdes::pyfinitdiff
    - numpy >=2.0,<3
    - pyvista
    - scipy
    - pydantic
    - tabulate
    - pathvalidate

about:
  home: https://github.com/MartinPdeS/SuPyMode
  license: MIT
  summary: "A package for light propagation in fiber optics component."
  description: SuPyMode is a library that uses Finite-difference and coupled mode theory to simulate light propagation in fiber optics tapered components.
  dev_url: https://github.com/MartinPdeS/SuPyMode
  doc_url: https://martinpdes.github.io/SuPyMode/
  license_file: LICENSE
  keywords:
    - optics
    - fiber optics
    - coupled mode theory
    - finite difference
    - physics
    - computational optics
    - simulation

files:
  include:
    - "SuPyMode/binary/*.so"

test:
  imports:
    - SuPyMode
  requires:
    - python {{ PY_VER }}*
    - python_abi 3.13.* *_cp313   # [py==313]
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ==1.5
    - coverage ==7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
