name: MacOS-x86_64-Workflow

permissions:
    contents: write

on:
    workflow_call:
        inputs:
            python_version_list:
                type: string
                required: false
                default: "['3.10']"


jobs:
    job_create_wheel:
        name: "Python ${{ matrix.python_version }}"
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                python_version: ${{ fromJson(inputs.python_version_list) }}
        steps:
          - name: "Checkout repository"
            uses: actions/checkout@v3
            with:
                submodules: true

          - uses: MartinPdeS/MPSActions/interpret_python_version@master
            with:
              python_version: ${{ matrix.python_version }}

          - name: "Build: Wheels"
            uses: pypa/cibuildwheel@v2.16.2
            with:
                output-dir: dist
            env:
                CC: /usr/bin/gcc
                CXX: /usr/bin/g++
                CIBW_BUILD: "${{ env.PYTHON_CP_VERSION }}-macosx_x86_64"
                CIBW_TEST_REQUIRES: ".[development]"
                CIBW_BUILD_VERBOSITY: 1
                CIBW_ARCHS: "x86_64"
                CIBW_PLATFORM: "macos"
                MACOSX_DEPLOYMENT_TARGET: "10.13"
                _PYTHON_HOST_PLATFORM: "macosx-10.13-x86_64"
                CIBW_TEST_COMMAND: 'pytest -s {project}/tests'
                CIBW_ENVIRONMENT_MACOS:
                    PROJ_WHEEL=true
                    PROJ_NETWORK=ON
                    MACOSX_DEPLOYMENT_TARGET=10.13
                CIBW_BEFORE_BUILD: |
                    mkdir build
                    cd build
                    cmake -G"Unix Makefiles" -DPYBIND11_PYTHON_VERSION=${{ matrix.python_version }}  ./..
                    make install
                    cd ..
                    ##### WTF: looks like if y put the requirement-dev before cmake install auditwheel will find too-recent symbols!!! (took me 8h to debug!)


          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "macos_x86_64_wheel_${{ env.PYTHON_CP_VERSION }}"
                path: ./dist/*




# -
