name: Deploy to Conda

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  conda_deployment:
    name: OS [${{ matrix.os }}]  Python [${{ matrix.python-version }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge, martinpdes
          conda-remove-defaults: true
          python-version: ${{ matrix.python-version }}

      - name: Conda environment creation and activation
        run: |
          conda install anaconda-client conda-build
          conda build . --python ${{ matrix.python-version }} --token ${{ secrets.ANACONDA_API_TOKEN }} --user martinpdes