# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages


on:
  workflow_run:
    workflows: ["Documentation"]  # This references the name of the first workflow
    types:
      - completed  # Run when the Documentation workflow is completed successfully


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ManyLinux_x86_64:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_documentation.yml@master
