name: Documentation

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: documentation-page-deployment
  cancel-in-progress: false

jobs:
  documentation:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_documentation.yml@v5
    with:
      python-version: "3.11"
      package-name: "SuPyMode"
      apt-package: xvfb jq
      deploy-pages: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) }}