name: Deploy to PyPi

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

permissions:
    contents: write

jobs:
    ManyLinux_x86_64:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout repository"
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
                submodules: 'true'

          - name: "Build: Wheels"
            uses: pypa/cibuildwheel@v2.19.2
            with:
                output-dir: dist
            env:
                CC: "/usr/bin/gcc"
                CXX: "/usr/bin/g++"

          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "manylinux_wheel_python"
            path: ./dist/*


    macos_x86_64:
        runs-on: macos-latest
        steps:
          - uses: maxim-lobanov/setup-xcode@v1
            with:
                xcode-version: '15.3'

          - name: "Checkout repository"
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
                submodules: true

          - name: Setup GNU Fortran
            uses: fortran-lang/setup-fortran@v1
            id: setup-fortran

          - name: "Build: Wheels"
            uses: pypa/cibuildwheel@v2.20.0
            with:
                output-dir: dist
            env:
                FC: "/usr/local/bin/gfortran"
                CIBW_ENVIRONMENT_MACOS:
                    MACOSX_DEPLOYMENT_TARGET=14.0
                    PROJ_WHEEL=true
                    PROJ_NETWORK=ON

          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "macos_x86_64_wheel"
                path: ./dist/*

    Windows_x86_64:
        runs-on: windows-latest
        steps:
          - name: "Checkout repository "
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
                submodules: true

          - uses: msys2/setup-msys2@v2
            with:
                path-type: inherit
                msystem: MINGW64
                install: >-
                    mingw-w64-x86_64-toolchain
                    mingw-w64-x86_64-cmake
                    mingw-w64-x86_64-openmp
                    mingw-w64-x86_64-ninja
                    mingw-w64-x86_64-gcc-fortran

          - uses: seanmiddleditch/gha-setup-ninja@master

          - name: "Build: Wheels"
            uses: pypa/cibuildwheel@v2.17.0
            with:
                output-dir: dist
            env:
                CMAKE_GENERATOR: Ninja
                CMAKE_MAKE_PROGRAM: ninja

          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "windows_wheel_python"
                path: ./dist/*

    publish_wheel:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [Windows_x86_64, ManyLinux_x86_64, macos_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: 3.11
                password: ${{ secrets.PYPI_API_TOKEN }}
