# Simple workflow for deploying static content to GitHub Pages
name: Deploy coverage

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]


# Sets permissions of the  GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ManyLinux_x86_64:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_coverage.yml@master
    with:
      python-version: "3.11"
    secrets:
      _GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
