name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  ManyLinux_x86_64:
    uses: ./.github/workflows/build_manylinux_x86_64.yml
    secrets: inherit
    with:
      python_version_list: "['3.10']"


  macos_x86_64:
    uses: ./.github/workflows/build_macos_x86_64.yml
    secrets: inherit
    with:
      python_version_list: "['3.10']"

  job_post_coverage:
    if: "contains(github.event.head_commit.message, '[publish]')"
    needs: [ManyLinux_x86_64]
    uses: ./.github/workflows/sub_deploy_coverage_badge.yml
    secrets: inherit
    with:
      python_version: "3.10"


  job_build_documentation:
    if: "contains(github.event.head_commit.message, '[publish]')"
    needs: [ManyLinux_x86_64]
    uses: ./.github/workflows/sub_deploy_documentation.yml
    secrets: inherit
    with:
      python_version: "3.10" #No documentation for python 3.7 (pickle5 not presentË˜)


  job_publish_wheel:
    if: "contains(github.event.head_commit.message, '[publish]')"
    needs: [ManyLinux_x86_64, macos_x86_64]
    uses: ./.github/workflows/sub_deploy_pypi.yml
    secrets: inherit
    with:
      python_version: "3.10"

# -
