name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    ManyLinux_x86_64:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_package_for_manylinux@master


    macos_x86_64:
        runs-on: macos-11
        steps:
          - uses: MartinPdeS/MPSActions/build_package_for_MacOS@master


    Windows_x86_64:
        runs-on: windows-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_package_for_Windows@master


    publish_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_coverage@master
            with:
                package-name: SuPyMode
                python-version: "3.11"
                auth: ${{ secrets.GIST_TOKEN }}
                gistID: 8e5ebf39ed694d3c90a790dffc0eff4f


    publish_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                package-name: SuPyMode
                python-version: "3.11" #no documentation for python 3.7 (pickle5 not presentË˜)


    publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Windows_x86_64, ManyLinux_x86_64, macos_x86_64, publish_documentation, publish_coverage]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: "3.11"
                password: ${{ secrets.PYPI_API_TOKEN }}

# -
