name: Deploy coverage

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  coverage:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_coverage.yml@v5
    with:
      python-version: "3.11"
      apt-package: xvfb
      coverage-package: SuPyMode
    secrets:
      _GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}