name: documentation_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: "3.9"

jobs:
  deploy_badge:
    name: "Publish documentation to RTD"
    runs-on: ubuntu-latest
    steps:
      - uses: MartinPdeS/MPSActions/install_package_on_manylinux@master
        with:
          python_version: ${{ inputs.python_version }}
          package_name: SuPyMode

      - uses: Bhacaz/checkout-files@v2
        with:
          files: docs requirements

      - name: "Build: documentation"
        run: |
          make -C docs html

      - name: "Upload: GitHub Pages"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}