name: badge_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: '3.10'

jobs:
  deploy_badge:
    name: "Badge deploy"
    runs-on: ubuntu-latest
    steps:

      - uses: Bhacaz/checkout-files@v2
        with:
          files: tests requirements

      - uses: MartinPdeS/MPSActions/install_package_on_manylinux@master
        with:
          python_version: ${{ inputs.python_version }}
          package_name: SuPyMode

      - uses: MartinPdeS/MPSActions/compute_unittest_coverage@master
        with:
          auth: ${{ secrets.MPdS_gist_token }}
          gistID: 16caa7bb2a83d5af36740e4a6a0f861d