name: badge_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: '3.10'

jobs:
  deploy_badge:
    name: "Badge deploy"
    runs-on: ubuntu-latest
    steps:

      - uses: Bhacaz/checkout-files@v2
        with:
          sparse-checkout: |
            tests
            .github
            requirements-development.txt
            requirements-validation.txt
            requirements-testing.txt
            requirements.txt

      - uses: ./.github/actions/install_package_ubuntu
        with:
          python_version: ${{ inputs.python_version }}

      - name: "Computing total coverage"
        run: |
          cd tests
          coverage run -p -m pytest -s .
          coverage combine
          coverage report -m --skip-covered
          coverage json -o ./CoverageReport.json
          export TOTAL=$(python -c "import json; print(json.load(open('CoverageReport.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV

      - name: "Upload: Coverage badge"
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.MPdS_gist_token }}
          gistID: 16caa7bb2a83d5af36740e4a6a0f861d
          filename: PyMieSim_coverage_badge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}