name: pypi_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: "3.9"

jobs:
  deploy_badge:
    name: "Publish wheel to PyPi"
    runs-on: ubuntu-latest
    steps:

      - name: "Set-up: Python ${{ inputs.python_version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python_version }}"

      - name: "Install: Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine

      - name: "Download: wheel"
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: "Publish: Wheel"
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          packages_dir: dist/*/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}